In [10]:
%cd ~/Documents/cvd-predictor/
from sklearnex import patch_sklearn
patch_sklearn()
import polars as pl
from CVD.utils import correlation_matrix, get_metrics, plot_feature_importances
from CVD.utils.encode import encode_data
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.naive_bayes import GaussianNB
from plotly.graph_objs._figure import Figure
from sklearn.svm import SVC
from xgboost import XGBClassifier
from lightgbm import LGBMClassifier
from sklearn.metrics import classification_report

C:\Users\dmitr\Documents\cvd-predictor

Intel(R) Extension for Scikit-learn* enabled (https://github.com/uxlfoundation/scikit-learn-intelex)

In [23]:
# df = pl.read_csv("data/intermediate/heart_cdc_2023.csv")
# df.write_parquet("data/intermediate/heart_cdc_2023.parquet")
df: pl.DataFrame = pl.read_parquet("data/intermediate/heart_cdc_2023.parquet")
df = encode_data(df)
columns =["GeneralHealth",	"PhysicalHealthDays","MentalHealthDays"	,"LastCheckupTime", "HadDepressiveDisorder", "HadSkinCancer"]
df=df.drop(columns)
df = df.drop_nulls()
# df.write_parquet("data/intermediate/heart_cdc_2023_cleaned.parquet")

In [24]:
df

shape: (323_400, 18)
┌─────┬──────────────────────┬───────────┬─────────┬───┬─────────────┬────────────┬──────────┬─────┐
│ Sex ┆ PhysicalActivities   ┆ HadAsthma ┆ HadCOPD ┆ … ┆ Sensory     ┆ Vaccinated ┆ Mobility ┆ CVD │
│ --- ┆ ---                  ┆ ---       ┆ ---     ┆   ┆ Impairments ┆ ---        ┆ ---      ┆ --- │
│ i64 ┆ i8                   ┆ i8        ┆ i8      ┆   ┆ ---         ┆ i64        ┆ i64      ┆ i64 │
│     ┆                      ┆           ┆         ┆   ┆ i64         ┆            ┆          ┆     │
╞═════╪══════════════════════╪═══════════╪═════════╪═══╪═════════════╪════════════╪══════════╪═════╡
│ 0   ┆ 1                    ┆ 1         ┆ 0       ┆ … ┆ 0           ┆ 0          ┆ 1        ┆ 0   │
│ 0   ┆ 0                    ┆ 1         ┆ 0       ┆ … ┆ 1           ┆ 1          ┆ 0        ┆ 0   │
│ 0   ┆ 0                    ┆ 0         ┆ 0       ┆ … ┆ 1           ┆ 1          ┆ 1        ┆ 0   │
│ 0   ┆ 0                    ┆ 1         ┆ 0       ┆ … ┆ 0           ┆ 1          ┆ 1        ┆ 0   │
│ 0   ┆ 0                    ┆ 1         ┆ 0       ┆ … ┆ 0           ┆ 1          ┆ 1        ┆ 0   │
│ …   ┆ …                    ┆ …         ┆ …       ┆ … ┆ …           ┆ …          ┆ …        ┆ …   │
│ 1   ┆ 1                    ┆ 0         ┆ 0       ┆ … ┆ 0           ┆ 1          ┆ 0        ┆ 0   │
│ 1   ┆ 0                    ┆ 1         ┆ 0       ┆ … ┆ 0           ┆ 0          ┆ 0        ┆ 0   │
│ 0   ┆ 1                    ┆ 1         ┆ 0       ┆ … ┆ 0           ┆ 0          ┆ 0        ┆ 0   │
│ 0   ┆ 0                    ┆ 1         ┆ 0       ┆ … ┆ 0           ┆ 1          ┆ 0        ┆ 0   │
│ 0   ┆ 0                    ┆ 1         ┆ 0       ┆ … ┆ 0           ┆ 0          ┆ 0        ┆ 0   │
└─────┴──────────────────────┴───────────┴─────────┴───┴─────────────┴────────────┴──────────┴─────┘

In [25]:
fig: Figure = correlation_matrix(df, ["Sex"])
fig.show()

In [26]:
X: pl.DataFrame = df.drop(["CVD"])
y: pl.Series = df["CVD"]

# scaler = StandardScaler()
# X[X.columns] = scaler.fit_transform(X)

In [27]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)
y_train.value_counts()

shape: (2, 2)
┌─────┬────────┐
│ CVD ┆ count  │
│ --- ┆ ---    │
│ i64 ┆ u32    │
╞═════╪════════╡
│ 1   ┆ 32937  │
│ 0   ┆ 225783 │
└─────┴────────┘

In [28]:
models = {
    "Logistic Regression": LogisticRegression(max_iter=10000, random_state=42),
    "Naive Bayes": GaussianNB(),
    "SVM": SVC(probability=True),  # SVM with probability
    "Random Forest": RandomForestClassifier(n_estimators=100, random_state=42),
    "LightGBM": LGBMClassifier(n_estimators=100, random_state=42), 
    "XGBoost": XGBClassifier(n_estimators=100, eval_metric="logloss", random_state=42),
}

In [ ]:
results: list[dict] = []
for name, model in models.items():
    model.fit(X_train, y_train)
    y_pred_prob: np.ndarray = model.predict_proba(X_test)[:, 1]
    y_pred_binary: np.ndarray = (y_pred_prob >= 0.5).astype(int)
    print(classification_report(y_test, y_pred_binary))
    results.append(get_metrics(y_test, y_pred_binary, name))
    plot_feature_importances(model, X, 15, name)

In [18]:
results_df = pl.DataFrame(results)
results_df

shape: (6, 6)
┌─────────────────────┬──────────┬───────────┬──────────┬──────────┬──────────┐
│ Model               ┆ Accuracy ┆ Precision ┆ Recall   ┆ F1 Score ┆ ROC AUC  │
│ ---                 ┆ ---      ┆ ---       ┆ ---      ┆ ---      ┆ ---      │
│ str                 ┆ f64      ┆ f64       ┆ f64      ┆ f64      ┆ f64      │
╞═════════════════════╪══════════╪═══════════╪══════════╪══════════╪══════════╡
│ Logistic Regression ┆ 0.848449 ┆ 0.547935  ┆ 0.342081 ┆ 0.421202 ┆ 0.643921 │
│ Naive Bayes         ┆ 0.799763 ┆ 0.425706  ┆ 0.693831 ┆ 0.527661 ┆ 0.756975 │
│ SVM                 ┆ 0.852011 ┆ 0.600907  ┆ 0.244015 ┆ 0.347086 ┆ 0.606435 │
│ Random Forest       ┆ 0.872495 ┆ 0.638753  ┆ 0.481123 ┆ 0.548845 ┆ 0.714416 │
│ LightGBM            ┆ 0.92608  ┆ 0.852518  ┆ 0.654696 ┆ 0.740625 ┆ 0.816465 │
│ XGBoost             ┆ 0.919326 ┆ 0.79151   ┆ 0.678177 ┆ 0.730474 ┆ 0.821923 │
└─────────────────────┴──────────┴───────────┴──────────┴──────────┴──────────┘