In [4]:
%cd ~/Documents/cvd-predictor/
from sklearnex import patch_sklearn
patch_sklearn()
import polars as pl
from CVD.utils import correlation_matrix, get_metrics, plot_feature_importances
from CVD.utils.encode import encode_data
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.naive_bayes import GaussianNB
from plotly.graph_objs._figure import Figure
from sklearn.svm import SVC
from xgboost import XGBClassifier
from lightgbm import LGBMClassifier
from sklearn.metrics import classification_report

C:\Users\timea\Documents\cvd-predictor

c:\Python311\Lib\site-packages\IPython\core\magics\osm.py:393: UserWarning:

This is now an optional IPython functionality, using bookmarks requires you to install the `pickleshare` library.

c:\Python311\Lib\site-packages\IPython\core\magics\osm.py:417: UserWarning:

This is now an optional IPython functionality, setting dhist requires you to install the `pickleshare` library.

Intel(R) Extension for Scikit-learn* enabled (https://github.com/uxlfoundation/scikit-learn-intelex)

In [5]:
# df = pl.read_csv("data/intermediate/heart_cdc_2023.csv")
# df.write_parquet("data/intermediate/heart_cdc_2023.parquet")
df: pl.DataFrame = pl.read_parquet("data/intermediate/heart_cdc_2023.parquet")
df = encode_data(df)
df = df.drop_nulls()
df.write_parquet("data/intermediate/heart_cdc_2023_cleaned.parquet")

In [6]:
fig: Figure = correlation_matrix(df, ["Sex"])
fig.show()

In [7]:
X: pl.DataFrame = df.drop(["CVD"])
y: pl.Series = df["CVD"]

# scaler = StandardScaler()
# X[X.columns] = scaler.fit_transform(X)

In [8]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)
y_train.value_counts()

shape: (2, 2)
┌─────┬───────┐
│ CVD ┆ count │
│ --- ┆ ---   │
│ i64 ┆ u32   │
╞═════╪═══════╡
│ 0   ┆ 45208 │
│ 1   ┆ 8686  │
└─────┴───────┘

In [9]:
models = {
    "Logistic Regression": LogisticRegression(max_iter=10000, random_state=42),
    "Naive Bayes": GaussianNB(),
    "SVM": SVC(probability=True),  # SVM with probability
    "Random Forest": RandomForestClassifier(n_estimators=100, random_state=42),
    "LightGBM": LGBMClassifier(n_estimators=100, random_state=42), 
    "XGBoost": XGBClassifier(n_estimators=100, eval_metric="logloss", random_state=42),
}

In [10]:
results: list[dict] = []
for name, model in models.items():
    model.fit(X_train, y_train)
    y_pred_prob: np.ndarray = model.predict_proba(X_test)[:, 1]
    y_pred_binary: np.ndarray = (y_pred_prob >= 0.5).astype(int)
    # print(classification_report(y_test, y_pred_binary))
    results.append(get_metrics(y_test, y_pred_binary, name))
    # plot_feature_importances(model, X, 15, name)

c:\Python311\Lib\site-packages\sklearn\base.py:486: UserWarning:

X has feature names, but SVC was fitted without feature names

[LightGBM] [Info] Number of positive: 8686, number of negative: 45208
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.007954 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 696
[LightGBM] [Info] Number of data points in the train set: 53894, number of used features: 23
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.161168 -> initscore=-1.649562
[LightGBM] [Info] Start training from score -1.649562

In [11]:
results_df = pl.DataFrame(results)
results_df

shape: (6, 6)
┌─────────────────────┬──────────┬───────────┬──────────┬──────────┬──────────┐
│ Model               ┆ Accuracy ┆ Precision ┆ Recall   ┆ F1 Score ┆ ROC AUC  │
│ ---                 ┆ ---      ┆ ---       ┆ ---      ┆ ---      ┆ ---      │
│ str                 ┆ f64      ┆ f64       ┆ f64      ┆ f64      ┆ f64      │
╞═════════════════════╪══════════╪═══════════╪══════════╪══════════╪══════════╡
│ Logistic Regression ┆ 0.848449 ┆ 0.547935  ┆ 0.342081 ┆ 0.421202 ┆ 0.643921 │
│ Naive Bayes         ┆ 0.799763 ┆ 0.425706  ┆ 0.693831 ┆ 0.527661 ┆ 0.756975 │
│ SVM                 ┆ 0.852011 ┆ 0.600907  ┆ 0.244015 ┆ 0.347086 ┆ 0.606435 │
│ Random Forest       ┆ 0.871456 ┆ 0.634969  ┆ 0.476519 ┆ 0.54445  ┆ 0.711937 │
│ LightGBM            ┆ 0.92608  ┆ 0.852518  ┆ 0.654696 ┆ 0.740625 ┆ 0.816465 │
│ XGBoost             ┆ 0.920291 ┆ 0.796117  ┆ 0.679558 ┆ 0.733234 ┆ 0.823056 │
└─────────────────────┴──────────┴───────────┴──────────┴──────────┴──────────┘